name: Bug report
description: Create a bug report
title: "[BUG] "
labels:
  - Awaiting Triage
assignees: []
body:
  - type: checkboxes
    id: searched
    attributes:
      label: "I searched for similar bugs"
      options:
        - label: "**I searched for similar bugs**"
          required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "🐛 Issue Description"
      description: "A clear, concise description of the bug."

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "📋 Reproduction Steps"
      description: "Step-by-step instructions to reproduce the issue."

  - type: textarea
    id: expected_behavior
    attributes:
      label: "🎯 Expected Behavior"
      description: "What you expected to happen."

  - type: textarea
    id: actual_behavior
    attributes:
      label: "💥 Actual Behavior"
      description: "What happened instead."

  - type: textarea
    id: screenshots_videos
    attributes:
      label: "🎥 Additional Screenshots / Videos"
      description: "If applicable, drag‑and‑drop images or a brief video here."

  - type: dropdown
    id: issue_severity
    attributes:
      label: "🚦 Issue Severity"
      description: "Select the severity level."
      options:
        - "Annoying: Minor visual glitches or small inconveniences."
        - "Minor: Affects gameplay slightly but not disruptive."
        - "Major: Impacts core mechanics, though still playable."
        - "Critical: Game‑breaking issues that render the game unplayable."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 🏷️ Additional Classification
        **Not a Bug:** Intended behavior.  
        **Duplicate:** Already reported issue.  
        **Won’t Fix:** Valid report but no fix planned.

  - type: textarea
    id: logs
    attributes:
      label: "📝 Logs / Error Messages"
      description: "Paste any relevant output."

  - type: markdown
    attributes:
      value: |
        > Feel free to remove any sections that don’t apply.  
        > Thanks for helping us improve the game!
