name: Bug report
description: Create a bug report
title: "[BUG] "
labels:
  - Awaiting Triage
assignees: []
body:
  - type: checkboxes
    id: searched
    attributes:
      label: "I searched for similar bugs"
      options:
        - label: "I searched for similar bugs"
          required: true

  - type: markdown
    attributes:
      value: |
        ### 🐛 Issue Description
        A clear and concise description of what the bug is.

  - type: textarea
    id: issue-description
    attributes:
      label: "Issue Description"
      description: "A clear and concise description of what the bug is."

  - type: markdown
    attributes:
      value: |
        ### 📋 Reproduction Steps
        Provide step-by-step instructions to reproduce the issue, if applicable.

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Reproduction Steps"
      description: "Step-by-step instructions to reproduce the issue."

  - type: textarea
    id: expected-behavior
    attributes:
      label: "🎯 Expected Behavior"
      description: "What you expected to happen."

  - type: textarea
    id: actual-behavior
    attributes:
      label: "💥 Actual Behavior"
      description: "What happened instead."

  - type: textarea
    id: screenshots-videos
    attributes:
      label: "🎥 Screenshots / Videos"
      description: "If applicable, add screenshots or a brief video."

  - type: dropdown
    id: issue-severity
    attributes:
      label: "🚦 Issue Severity"
      description: "Select the severity level."
      options:
        - "Annoying: Minor visual glitches or small inconveniences that don’t impact functionality."
        - "Minor: Affects gameplay slightly but not disruptive."
        - "Major: Impacts core mechanics, though still playable."
        - "Critical: Game-breaking issues that render the game unplayable."

  - type: checkboxes
    id: additional-classification
    attributes:
      label: "🏷️ Additional Classification"
      options:
        - label: "Not a Bug: Intended behavior."
        - label: "Duplicate: Already reported issue."
        - label: "Won’t Fix: Valid report but no fix planned."

  - type: markdown
    attributes:
      value: >
        > Feel free to remove any sections that don’t apply.  
        > Thanks for helping us improve the game!
